# H2 DB configuration
spring:
  datasource:
    url:  jdbc:h2:mem:patika_0401
    driverClassName:  org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform:  org.hibernate.dialect.H2Dialect
  h2:
    console.enabled:  true
